AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create ECS Fargate"

Parameters:
  EnvironmentType:
    Type: String

  EnvironmentName:
    Type: String

  PrivateSubnet1:
    Type: String

  PrivateSubnet2:
    Type: String

  ECSSecurityGroup:
    Type: String

  DesiredCount:
    Type: String

  ImageUrlApp:
    Type: String

  RDSWriterEnpointAddr:
    Type: String

  RDSReaderEnpointAddr:
    Type: String

  RDSEnpointPort:
    Type: String

  TargetGroupAPP:
    Type: String

  FileSystemId:
    Type: String

  AccessPointIdDataApp:
    Type: String


Conditions:
  isProdEnvironmentType: !Equals [!Ref EnvironmentType, prod]


Resources:
  LogGroupApp:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${EnvironmentName}-App
      RetentionInDays: 365

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-ECSTaskRole
      Description: Role access to other AWS resources
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - ecs-tasks.amazonaws.com
          Action: 
            - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      Path: /

  TaskDefinitionApp:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - LogGroupApp
    Properties:
      Family: !Sub ${EnvironmentName}-TD-App
      Cpu: !If [isProdEnvironmentType, 512, 256]
      Memory: !If [isProdEnvironmentType, 1024, 512]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !Ref ECSTaskRole
      ContainerDefinitions:
        - Name: ContainerApp
          Cpu: !If [isProdEnvironmentType, 512, 256]
          MemoryReservation: !If [isProdEnvironmentType, 1024, 512]
          Image: !Ref ImageUrlApp
          PortMappings:
            - ContainerPort: 8554
          MountPoints:
            - SourceVolume: efs-app
              ContainerPath: /mnt/app
          Environment:
            - Name: DB_URL_WRITE
              Value: !Sub 'jdbc:mysql:aurora//${RDSWriterEnpointAddr}:${RDSEnpointPort}/AURORADB'
            - Name: DB_URL_READ
              Value: !Sub 'jdbc:mysql:aurora//${RDSReaderEnpointAddr}:${RDSEnpointPort}/AURORADB'
          StopTimeout: 30
          Ulimits:
            - Name: 'nofile'
              SoftLimit: 65536
              HardLimit: 65536
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${EnvironmentName}-App"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: App
      Volumes:
        - Name: efs-app
          EFSVolumeConfiguration:
            FilesystemId: !Ref FileSystemId
            TransitEncryption: ENABLED
            AuthorizationConfig:
              AccessPointId: !Ref AccessPointIdDataApp
              IAM: DISABLED
      Tags:
        - 
          Key: Environment
          Value: !Ref EnvironmentName

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${EnvironmentName}-ECS-Cluster
      ClusterSettings: 
        - 
          Name: containerInsights
          Value: 'enabled'
      CapacityProviders: 
        - FARGATE_SPOT
        - FARGATE
      Tags:
        - 
          Key: Environment
          Value: !Ref EnvironmentName
        - 
          Key: Name
          Value: !Sub ${EnvironmentName}-ECS-Cluster

  ServiceApp:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub "${EnvironmentName}-APP"
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: !Ref DesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ECSSecurityGroup
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
      TaskDefinition: !Ref TaskDefinitionApp
      EnableExecuteCommand: 'true'
      HealthCheckGracePeriodSeconds: 60
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroupAPP
          ContainerPort: 8554
          ContainerName: ContainerApp
      Tags:
        - 
          Key: Environment
          Value: !Ref EnvironmentName
        - 
          Key: Name
          Value: !Sub ${EnvironmentName}-APP