AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create VPC Endpoints"

Parameters:
  VpcID:
    Type: String

  PrivateSubnet1:
    Type: String

  PrivateSubnet2:
    Type: String

  VPCEnpointSecurityGroup:
    Type: String


Resources:
  MonitoringEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref VPCEnpointSecurityGroup
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.monitoring"
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      VpcEndpointType: 'Interface'
      VpcId: !Ref VpcID

  LogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref VPCEnpointSecurityGroup
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.logs"
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      VpcEndpointType: 'Interface'
      VpcId: !Ref VpcID

  SecretsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref VPCEnpointSecurityGroup
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.secretsmanager"
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      VpcEndpointType: 'Interface'
      VpcId: !Ref VpcID